### ISSUE TITLE
Bad URI causes crash

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/nodebb-plugin-iframely#23]
When the plugin processes the following:
`<a href="mailto:anoy%*@(*&amp;#...&lt;NO">anoy%*@(*&amp;#...&lt;NO</a>`

...it crashes:

```
2/6 08:47 [11950] - error: URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.iframely.replace (/home/boomzilla/nodebb/node_modules/nodebb-plugin-iframely/library.js:105:21)
    at Object.iframely.replace [as method] (/home/boomzilla/nodebb/node_modules/nodebb-plugin-iframely/library.js:79:12)
    at /home/boomzilla/nodebb/src/plugins/hooks.js:134:12
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:375:13
    at Immediate.iterate [as _onImmediate] (/home/boomzilla/nodebb/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-iframely/commit/fc67d0fe239fc03b61afb025eb4e0c59fe3d015b
