### ISSUE TITLE
TypeError: Cannot read property 'thumbnail' of undefined

### ISSUE THREAD

**Issue by rsramek** [NodeBB/nodebb-plugin-iframely#24]
Upon swapping from iframe.ly to self-hosted iframely instance, nodebb keeps crashing with:

15/6 11:09 [26918] - error: TypeError: Cannot read property 'thumbnail' of undefined
    at getImage (/root/nodebb/node_modules/nodebb-plugin-iframely/library.js:474:26)
    at /root/nodebb/node_modules/nodebb-plugin-iframely/library.js:143:19
    at /root/nodebb/node_modules/async/lib/async.js:375:13
    at iterate (/root/nodebb/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/root/nodebb/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/root/nodebb/node_modules/async/lib/async.js:374:15)
    at /root/nodebb/node_modules/nodebb-plugin-iframely/library.js:133:11
    at fn (/root/nodebb/node_modules/async/lib/async.js:746:34)
    at /root/nodebb/node_modules/async/lib/async.js:1213:16
    at /root/nodebb/node_modules/async/lib/async.js:166:37

The endpoint address is specified as "http://w.x.y.z:8061". Interestingly, server logs do not show a successful request, however I presume this is correctly configured because if the address is incorrect or lacking the http://, nothing happens.

I'm quite confused by this, because if I query the backend manually, I do get the thumbnail populated.

**Comment by nleush** [comment]
Try set endpoint: http://w.x.y.z:8061/iframely

**Comment by rsramek** [comment]
Ah! That helped. Thanks a lot and many thanks for the quick reply!

**Comment by nleush** [comment]
You are welcome.
