### ISSUE TITLE
Server crash after installing this plugin

### ISSUE THREAD

**Issue by AndreasKnight** [NodeBB/nodebb-plugin-iframely#4]
```

30/9 19:15 [9350] - info: Time: Wed Sep 30 2015 19:15:17 GMT+0200 (CEST)
30/9 19:15 [9350] - info: Initializing NodeBB v0.8.2
30/9 19:15 [9350] - verbose: * using configuration stored in: /root/NBB/config.json
30/9 19:15 [9350] - verbose: * using redis store at 127.0.0.1:6379
30/9 19:15 [9350] - verbose: * using themes stored in: /root/NBB/node_modules
Warning: Redis server does not require a password, but a password was supplied.
30/9 19:15 [9350] - verbose: Checking dependencies for outdated modules
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
30/9 19:15 [9350] - verbose: [notifications.init] Registering jobs.
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
30/9 19:15 [9350] - info: [themes] Using theme nodebb-theme-persona
30/9 19:15 [9350] - verbose: [plugins] Initializing plugins system
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-dbsearch
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-markdown
30/9 19:15 [9350] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-markdown
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-mentions
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-mentions
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-google-analytics
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-analytics
30/9 19:15 [9350] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-rewards-essentials
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji-extended
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji-extended
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-extended
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-spam-be-gone
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-spam-be-gone
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-spam-be-gone
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-desktop-notifications
30/9 19:15 [9350] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-desktop-notifications
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-desktop-notifications
30/9 19:15 [9350] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-youtube
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-youtube
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-question-and-answer
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-question-and-answer
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-question-and-answer
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-imgur
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-recent-cards
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-recent-cards
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-recent-cards
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-emailer-mandrill
30/9 19:15 [9350] - warn: [plugins/nodebb-plugin-sso-facebook] Hook `filter:user.delete` is deprecated, please use an alternative
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-sso-facebook
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-facebook
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-composer-default
30/9 19:15 [9350] - verbose: [plugins] Found 10 js file(s) for plugin nodebb-plugin-composer-default
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-custom-pages
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-custom-pages
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-custom-pages
30/9 19:15 [9350] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-iframely
30/9 19:15 [9350] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-iframely
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-plugin-iframely
30/9 19:15 [9350] - verbose: [plugins] Found 4 js file(s) for plugin nodebb-theme-persona
30/9 19:15 [9350] - verbose: [plugins] Loaded plugin: nodebb-theme-persona

30/9 19:15 [9350] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-desktop-notifications
  * nodebb-plugin-youtube

30/9 19:15 [9350] - info: [plugins] Plugins OK
30/9 19:15 [9350] - verbose: [meta/css] Minifying LESS/CSS
30/9 19:15 [9350] - verbose: [sounds] Sounds OK
30/9 19:15 [9350] - verbose: [meta/templates] Compiling templates
30/9 19:15 [9350] - verbose: [meta/templates] Successfully compiled templates.
30/9 19:15 [9350] - verbose: [meta/css] admin.css committed to disk.
30/9 19:15 [9350] - verbose: [meta/js] Minification complete
30/9 19:15 [9350] - verbose: [hotswap] Router with id `auth` replaced successfully
30/9 19:15 [9350] - verbose: [meta/css] stylesheet.css committed to disk.
30/9 19:15 [9350] - info: [plugins/spam-be-gone] Settings loaded
30/9 19:15 [9350] - verbose: [hotswap] Router with id `plugins` replaced successfully
30/9 19:15 [9350] - verbose: [plugins] All plugins reloaded and rerouted
30/9 19:15 [9350] - error: TypeError: Cannot call method 'split' of undefined
    at /root/NBB/node_modules/nodebb-plugin-iframely/library.js:36:39
    at /root/NBB/src/meta/settings.js:12:4
    at try_callback (/root/NBB/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/root/NBB/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/root/NBB/node_modules/redis/index.js:309:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (/root/NBB/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/root/NBB/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/root/NBB/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/root/NBB/node_modules/redis/index.js:91:14)
3 restarts in 10 seconds, most likely an error on startup. Halting.
```

Please fix. Thanks :+1:

**Comment by julianlam** [comment]
Fixed by @iparamonau, published as v0.5.3 now :smile: 

6d8811f4c56c62d58b6dc3c36b1970cffe068900
